### ISSUE TITLE
Conda package outdated

### ISSUE THREAD

**Issue by FlyinTeller** [hzi-bifo/Haploflow#12]
Hi,

the conda package is at some version from April and is called v0.1, while the github has a release from June with version 1.0. Any chance you could update the conda package?

**Comment by AlphaSquad** [comment]
True and thank you for the reminder. 
I have set up `autobump` on bioconda now and the new `1.0` version should hopefully appear soon. I will leave this issue open until that happened

**Comment by hoelzer** [comment]
Hi, it seems the conda is still outdated?

**Comment by AlphaSquad** [comment]
Unfortunately, yes. The PR for updating the package does not merge automatically, so it seems like I have to set up a PR manually - something I unfortunately did not get around to do so far

**Comment by andre-geldenhuis** [comment]
@AlphaSquad Do you mind if I create the pull request to bioconda with the updated haploflow v1.0?  I've got the recipe tested - just want to check you're all good with me doing that.

**Comment by AlphaSquad** [comment]
That would be great, thank you very much!

**Comment by andre-geldenhuis** [comment]
Bioconda merged my pull request, so the bioconda version is now up to date
