### ISSUE TITLE
Input compressed file?

### ISSUE THREAD

**Issue by ammaraziz** [hzi-bifo/Haploflow#17]
Can haploflow handle fastq.gz (compressed) files? It seems to me that it doesn't, resulting in an error.

This would save a good chunk of time and space. Currently I have to uncompress the fastq.gz files then run haploflow followed by deleting the fastq files.

**Comment by AlphaSquad** [comment]
True, Haploflow was not able to deal with compressed files. I added handling for `gz`ipped files now. To still be able to handle uncompressed files, Haploflow performs a "name-check" for "`gz`", so if your file gzip-file ends with `gz` it should work.

**Comment by ammaraziz** [comment]
Thank you @AlphaSquad !
