### ISSUE TITLE
Problem with HIV-3 test date set

### ISSUE THREAD

**Issue by Viola-TA** [hzi-bifo/Haploflow#19]
Hello all,
I have installed haploflow in its own environment.
_haploflow --help_ also shows me the corresponding result. 
Then I wanted to test the function of haploflow with the HIV_3_toy-file.
But I get an error that I don't understand. And so far I have not been able to find a solution.

**My used command:**
./haploflow --read-file ~/Downloads/HIV_3_toy.fq.gz --out Test_Haploflow --log Test_Haploflow/log

**My mistake:**
terminate called after throwing an instance of 'std::out_of_range'.
  what(): vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)

The folder _Test_Haploflow_ is created. There are two files in this order: Cov.tsv (o bytes); log (448 bytes).

The **log file** is very short:
Options used: 
strict 5, k 41, error-rate 0.02, two-strain False, long contigs: False, filter 500, threshold -1
Building deBruijnGraph...
Building deBruijnGraph took 0.000351 seconds.
deBruijnGraph has 0 vertices
Building unitig graph from deBruijn graph...
Getting connected components
Getting CCs took 7e-06 seconds
Calculating coverage distribution
Calculating coverage distribution took 1.6e-05 seconds
Printing the biggest graph with 0 k-mers

Can anyone help me with this problem?
Many thanks,
Viola

**Comment by AlphaSquad** [comment]
Hi Viola,
unfortunately in the bioconda version of Haploflow (`1.0`) the handling of compressed files was not added yet, so you would need to `gunzip` the toy data set first.
Let me know if that resolves your error, thanks!

**Comment by Viola-TA** [comment]
Yes, I was able to start the programme with the decompressed file.
But it only ran for a few seconds. The folder was created with three files: contigs.fa (with 3 contigs), Cov.tsv, log.
But the subfolders are missing.
[log.txt](https://github.com/hzi-bifo/Haploflow/files/11398074/log.txt)

**Comment by Viola-TA** [comment]
Ah, ok. Then Haploflow seems to be running error-free for me now.
Many thanks for the information and your help.
