### ISSUE TITLE
Build Script Fails Due to Missing `ronn` Dependency

### ISSUE THREAD

**Issue by Donaim** [hzi-bifo/Haploflow#22]
While attempting to build the project on Ubuntu 18.04, the build script (build.sh) failed with the following error:

```shell
E: Unable to locate package ronn
```

# Steps to Reproduce

Clone the repository to an Ubuntu 22.04 system.

Run
```shell
./build.sh.
```

# Expected Behavior
The build script should install all necessary dependencies and successfully build the project.

# Actual Behavior
The build script fails because it cannot locate the `ronn` package.

# System Information
OS: Ubuntu 22.04.2
Commit SHA: `9a5a0ff6c3a0435e723e41f98fe82ec2ad19cf50`

# Suggested Fix
It seems that the `ronn` package is not explicitly installed by the build.sh script. Adding `ronn` to the list of packages to install would resolve this issue.

**Comment by AlphaSquad** [comment]
Thank you for bringing this to my attention. It seems like the listed dependency is `ruby-ronn` instead of `ronn`.
